# Generated by Django 5.2 on 2025-04-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
