# Generated by Django 5.2 on 2025-05-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_alter_trade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='agent',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
