# Generated by Django 5.1.3 on 2025-06-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_trade_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
